// GET ALL RAW MATERIALS -
export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

// GET ALL RAW MATERIALS DETAILS -
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

// LOGIN -
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// REGISTER -
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// LOAD USER -
export const LOAD_REQUEST = "LOAD_REQUEST";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const LOAD_FAIL = "LOAD_FAIL";

// LOGOUT USER -
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

// PROFILE -
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

// PASSWORD -
export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

// FORGOT PASSWORD -
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

// RESET PASSWORD -
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

// EXPENSE
export const EXPENSE_REQUEST = "EXPENSE_REQUEST";
export const EXPENSE_SUCCESS = "EXPENSE_SUCCESS";
export const EXPENSE_FAIL = "EXPENSE_FAIL";
export const GET_ALL_EXPENSE_REQUEST = "GET_ALL_EXPENSE_REQUEST";
export const GET_ALL_EXPENSE_SUCCESS = "GET_ALL_EXPENSE_SUCCESS";
export const GET_ALL_EXPENSE_FAIL = "GET_ALL_EXPENSE_FAIL";

// FORMULA
export const GET_FORMULA_PRODUCTS_REQUEST = "GET_FORMULA_PRODUCTS_REQUEST";
export const GET_FORMULA_PRODUCTS_SUCCESS = "GET_FORMULA_PRODUCTS_SUCCESS";
export const GET_FORMULA_PRODUCTS_FAIL = "GET_FORMULA_PRODUCTS_FAIL";
export const CREATE_FORMULA_REQUEST = "CREATE_FORMULA_REQUEST";
export const CREATE_FORMULA_SUCCESS = "CREATE_FORMULA_SUCCESS";
export const CREATE_FORMULA_FAIL = "CREATE_FORMULA_FAIL";
export const GET_ALL_USER_FORMULA_REQUEST = "GET_ALL_USER_FORMULA_REQUEST";
export const GET_ALL_USER_FORMULA_SUCCESS = "GET_ALL_USER_FORMULA_SUCCESS";
export const GET_ALL_USER_FORMULA_FAIL = "GET_ALL_USER_FORMULA_FAIL";
export const CREATE_BATCH_REQUEST = "CREATE_BATCH_REQUEST";
export const CREATE_BATCH_SUCCESS = "CREATE_BATCH_SUCCESS";
export const CREATE_BATCH_FAIL = "CREATE_BATCH_FAIL";
export const GET_ALL_BATCHES_REQUEST = "GET_ALL_BATCHES_REQUEST";
export const GET_ALL_BATCHES_SUCCESS = "GET_ALL_BATCHES_SUCCESS";
export const GET_ALL_BATCHES_FAIL = "GET_ALL_BATCHES_FAIL";
export const USE_BATCH_REQUEST = "USE_BATCH_REQUEST";
export const USE_BATCH_SUCCESS = "USE_BATCH_SUCCESS";
export const USE_BATCH_FAIL = "USE_BATCH_FAIL";

// SALES -
export const CREATE_SALES_REQUEST = "CREATE_SALES_REQUEST";
export const CREATE_SALES_SUCCESS = "CREATE_SALES_SUCCESS";
export const CREATE_SALES_FAIL = "CREATE_SALES_FAIL";
export const GET_SALES_REQUEST = "GET_SALES_REQUEST";
export const GET_SALES_SUCCESS = "GET_SALES_SUCCESS";
export const GET_SALES_FAIL = "GET_SALES_FAIL";

// ADMIN USERS -
export const GET_ADMIN_USERS_REQUEST = "GET_ADMIN_USERS_REQUEST";
export const GET_ADMIN_USERS_SUCCESS = "GET_ADMIN_USERS_SUCCESS";
export const GET_ADMIN_USERS_FAIL = "GET_ADMIN_USERS_FAIL";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const UPDATE_ADMIN_USER_REQUEST = "UPDATE_ADMIN_USER_REQUEST";
export const UPDATE_ADMIN_USER_SUCCESS = "UPDATE_ADMIN_USER_SUCCESS";
export const UPDATE_ADMIN_USER_FAIL = "UPDATE_ADMIN_USER_FAIL";
export const UPDATE_ADMIN_USER_RESET = "UPDATE_ADMIN_USER_RESET";
export const GET_ADMIN_USER_REQUEST = "GET_ADMIN_USER_REQUEST";
export const GET_ADMIN_USER_SUCCESS = "GET_ADMIN_USER_SUCCESS";
export const GET_ADMIN_USER_FAIL = "GET_ADMIN_USER_FAIL";

// ADMIN SALES -
export const GET_ADMIN_SALES_REQUEST = "GET_ADMIN_SALES_REQUEST";
export const GET_ADMIN_SALES_SUCCESS = "GET_ADMIN_SALES_SUCCESS";
export const GET_ADMIN_SALES_FAIL = "GET_ADMIN_SALES_FAIL";
export const DELETE_ADMIN_SALE_REQUEST = "DELETE_ADMIN_SALE_REQUEST";
export const DELETE_ADMIN_SALE_SUCCESS = "DELETE_ADMIN_SALE_SUCCESS";
export const DELETE_ADMIN_SALE_FAIL = "DELETE_ADMIN_SALE_FAIL";

// ADMIN EXPENSE -
export const GET_ADMIN_EXPENSE_REQUEST = "GET_ADMIN_EXPENSE_REQUEST";
export const GET_ADMIN_EXPENSE_SUCCESS = "GET_ADMIN_EXPENSE_SUCCESS";
export const GET_ADMIN_EXPENSE_FAIL = "GET_ADMIN_EXPENSE_FAIL";
export const DELETE_ADMIN_EXPENSE_REQUEST = "DELETE_ADMIN_EXPENSE_REQUEST";
export const DELETE_ADMIN_EXPENSE_SUCCESS = "DELETE_ADMIN_EXPENSE_SUCCESS";
export const DELETE_ADMIN_EXPENSE_FAIL = "DELETE_ADMIN_EXPENSE_FAIL";
export const UPDATE_ADMIN_EXPENSE_REQUEST = "UPDATE_ADMIN_EXPENSE_REQUEST";
export const UPDATE_ADMIN_EXPENSE_SUCCESS = "UPDATE_ADMIN_EXPENSE_SUCCESS";
export const UPDATE_ADMIN_EXPENSE_FAIL = "UPDATE_ADMIN_EXPENSE_FAIL";
export const UPDATE_ADMIN_EXPENSE_RESET = "UPDATE_ADMIN_EXPENSE_RESET";

// ADMIN RAW MATERIALS -
export const GET_ADMIN_PRODUCTS_REQUEST = "GET_ADMIN_PRODUCTS_REQUEST";
export const GET_ADMIN_PRODUCTS_SUCCESS = "GET_ADMIN_PRODUCTS_SUCCESS";
export const GET_ADMIN_PRODUCTS_FAIL = "GET_ADMIN_PRODUCTS_FAIL";
export const DELETE_ADMIN_PRODUCTS_REQUEST = "DELETE_ADMIN_PRODUCTS_REQUEST";
export const DELETE_ADMIN_PRODUCTS_SUCCESS = "DELETE_ADMIN_PRODUCTS_SUCCESS";
export const DELETE_ADMIN_PRODUCTS_FAIL = "DELETE_ADMIN_PRODUCTS_FAIL";
export const CREATE_ADMIN_PRODUCTS_REQUEST = "CREATE_ADMIN_PRODUCTS_REQUEST";
export const CREATE_ADMIN_PRODUCTS_SUCCESS = "CREATE_ADMIN_PRODUCTS_SUCCESS";
export const CREATE_ADMIN_PRODUCTS_FAIL = "CREATE_ADMIN_PRODUCTS_FAIL";
export const UPDATE_ADMIN_PRODUCT_REQUEST = "UPDATE_ADMIN_PRODUCT_REQUEST";
export const UPDATE_ADMIN_PRODUCT_SUCCESS = "UPDATE_ADMIN_PRODUCT_SUCCESS";
export const UPDATE_ADMIN_PRODUCT_FAIL = "UPDATE_ADMIN_PRODUCT_FAIL";
export const UPDATE_ADMIN_PRODUCT_RESET = "UPDATE_ADMIN_PRODUCT_RESET";

// ADMIN FORMULA -
export const GET_ADMIN_FORMULA_REQUEST = "GET_ADMIN_FORMULA_REQUEST";
export const GET_ADMIN_FORMULA_SUCCESS = "GET_ADMIN_FORMULA_SUCCESS";
export const GET_ADMIN_FORMULA_FAIL = "GET_ADMIN_FORMULA_FAIL";
export const ADMIN_FORMULA_STATUS_REQUEST = "ADMIN_FORMULA_STATUS_REQUEST";
export const ADMIN_FORMULA_STATUS_SUCCESS = "ADMIN_FORMULA_STATUS_SUCCESS";
export const ADMIN_FORMULA_STATUS_FAIL = "ADMIN_FORMULA_STATUS_FAIL";
export const ADMIN_FORMULA_UPDATE_REQUEST = "ADMIN_FORMULA_UPDATE_REQUEST";
export const ADMIN_FORMULA_UPDATE_SUCCESS = "ADMIN_FORMULA_UPDATE_SUCCESS";
export const ADMIN_FORMULA_UPDATE_FAIL = "ADMIN_FORMULA_UPDATE_FAIL";
export const ADMIN_FORMULA_UPDATE_RESET = "ADMIN_FORMULA_UPDATE_RESET";
export const ADMIN_FORMULA_DELETE_REQUEST = "ADMIN_FORMULA_DELETE_REQUEST";
export const ADMIN_FORMULA_DELETE_SUCCESS = "ADMIN_FORMULA_DELETE_SUCCESS";
export const ADMIN_FORMULA_DELETE_FAIL = "ADMIN_FORMULA_DELETE_FAIL";

// ADMIN BATCHES -
export const ADMIN_BATCHES_GET_REQUEST = "ADMIN_BATCHES_GET_REQUEST";
export const ADMIN_BATCHES_GET_SUCCESS = "ADMIN_BATCHES_GET_SUCCESS";
export const ADMIN_BATCHES_GET_FAIL = "ADMIN_BATCHES_GET_FAIL";
export const ADMIN_BATCHES_UPDATE_REQUEST = "ADMIN_BATCHES_UPDATE_REQUEST";
export const ADMIN_BATCHES_UPDATE_SUCCESS = "ADMIN_BATCHES_UPDATE_SUCCESS";
export const ADMIN_BATCHES_UPDATE_FAIL = "ADMIN_BATCHES_UPDATE_FAIL";
export const ADMIN_BATCHES_UPDATE_RESET = "ADMIN_BATCHES_UPDATE_RESET";
export const ADMIN_BATCHES_DELETE_REQUEST = "ADMIN_BATCHES_DELETE_REQUEST";
export const ADMIN_BATCHES_DELETE_SUCCESS = "ADMIN_BATCHES_DELETE_SUCCESS";
export const ADMIN_BATCHES_DELETE_FAIL = "ADMIN_BATCHES_DELETE_FAIL";

// CLEAR ERRORS -
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// CLEAR MESSAGES -
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";

// CLEAR_SUCCESS
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
